name: Run ChatTTS

on:
  workflow_dispatch:

jobs:
  run-tts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install torch soundfile numpy
          pip install git+https://github.com/2noise/ChatTTS.git

      - name: Run TTS
        run: |
          python - <<'EOF'
          import ChatTTS
          chat = ChatTTS.Chat()
          chat.load_models()

          texts = ["Hello! This is ChatTTS running on GitHub Actions."]
          wavs = chat.infer(texts)

          import soundfile as sf
          sf.write("output.wav", wavs[0], 24000)
          EOF

      - name: Upload Audio
        uses: actions/upload-artifact@v3
        with:
          name: chattts-audio
          path: output.wav
