name: ChatTTS Full Setup and Verify

on:
  workflow_dispatch:

jobs:
  run_chattts:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: 3.10

    - name: Upgrade pip and install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install torch==2.2.2+cpu pyyaml ChatTTS

    - name: Download ChatTTS models
      run: |
        mkdir -p asset/tokenizer
        # Replace below URLs with real model/tokenizer URLs
        curl -L -o asset/GPT.pt "https://example.com/path/to/GPT.pt"
        curl -L -o asset/vocoder.pt "https://example.com/path/to/vocoder.pt"
        # For tokenizer, you may need to download multiple files or a zipped tokenizer folder
        # curl -L -o asset/tokenizer/tokenizer_file "https://example.com/path/to/tokenizer_file"

    - name: Run ChatTTS inference and save output
      run: |
        python << 'EOF'
        import os
        from ChatTTS import ChatTTS

        chat = ChatTTS.Chat()
        chat.load_models(
            gpt_model_path="asset/GPT.pt",
            vocoder_model_path="asset/vocoder.pt",
            tokenizer_path="asset/tokenizer"
        )
        text = "Hello from GitHub Actions with ChatTTS!"
        audio = chat.infer(text)
        os.makedirs("output", exist_ok=True)
        with open("output/test.wav", "wb") as f:
            f.write(audio)
        print("Inference done, audio saved to output/test.wav")
        EOF

    - name: Upload audio artifact for download
      uses: actions/upload-artifact@v4
      with:
        name: chattts-audio
        path: output/test.wav
        
