name: RVC Inference Workflow

on:
  workflow_dispatch:

jobs:
  run-inference:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Setup Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Install system dependencies
      run: sudo apt-get update && sudo apt-get install -y ffmpeg

    - name: Install RVC package
      run: pip install git+https://github.com/RVC-Project/Retrieval-based-Voice-Conversion

    - name: Create assets folder structure
      run: |
        mkdir -p assets/hubert
        mkdir -p assets/pretrained

    - name: Download pretrained models
      run: |
        curl -L -o assets/hubert/hubert_inputs.pth https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/raw/main/assets/hubert/hubert_inputs.pth
        curl -L -o assets/Synthesizer_inputs.pth https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/raw/main/assets/Synthesizer_inputs.pth
        curl -L -o assets/pretrained/D_RigelFT_40k_9801520.pth https://huggingface.co/MUSTAR/Rigel-rvc-base-pretrained-model/resolve/main/Rigel_40k_Base_and_FineTuned/FineTuned-model_40k/Alpha/D_RigelFT_40k_9801520.pth

    - name: Download input audio
      run: curl -L -o input.wav https://storage.googleapis.com/chatterbox-demo-samples/samples/duff_random_woman_podcast.wav

    - name: Run inference via Python API
      run: |
        python -c "
         from pathlib import Path
         from scipy.io import wavfile
         from rvc.modules.vc.modules import VC

         vc = VC()
         vc.get_vc('assets/pretrained/D_RigelFT_40k_9801520.pth')
         tgt_sr, audio_opt, _, _ = vc.vc_inference(1, Path('input.wav'))
         wavfile.write('output.wav', tgt_sr, audio_opt)"

    - name: Upload output wav
      uses: actions/upload-artifact@v4
      with:
        name: rvc_inference_output
        path: output.wav
        
