name: rvc-sample

on:
  workflow_dispatch:

jobs:
  run-rvc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install RVC
        run: |
          # First install torch/torchaudio from PyTorch CPU index
          pip install torch==2.2.2 torchaudio --index-url https://download.pytorch.org/whl/cpu
          # Then install the rest from PyPI (default)
          pip install librosa soundfile numpy
          pip install fairseq2
          pip install TTS
          # Clone and install RVC
          # git clone https://github.com/RVC-Project/Retrieval-based-Voice-Conversion.git rvc
          # cd rvc
      - name: Clone RVC WebUI
        run: |
          git clone https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI.git rvc
          cd rvc

      - name: Download pretrained models
        run: |
          cd rvc
          python tools/download_models.py
          
      - name: Download example input
        run: |
          curl -L -o input.wav https://storage.googleapis.com/chatterbox-demo-samples/samples/numbers_random_woman.wav

      - name: Run RVC Inference
        run: |
          cd rvc
          # Adjust these paths if needed based on your model selection
          python infer_cli.py \
            --input_path ../input.wav \
            --model_path assets/pretrained_v2/G40k.pth \
            --config_path configs/config.json \
            --hubert_path assets/hubert/hubert_base.pt \
            --index_path assets/pretrained_v2/added_IVF.index \
            --rmvpe_path rmvpe.pt \
            --output_path ../rvc_output.wav

      - name: Upload RVC sample
        uses: actions/upload-artifact@v4
        with:
          name: rvc_sample
          path: rvc_output.wav
