name: rvc-sample

on:
  workflow_dispatch:

jobs:
  run-rvc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install RVC
        run: |
          # First install torch/torchaudio from PyTorch CPU index
          pip install torch==2.2.2 torchaudio --index-url https://download.pytorch.org/whl/cpu
          # Then install the rest from PyPI (default)
          pip install librosa soundfile numpy
          pip install fairseq2
          pip install TTS
          # Clone and install RVC
          git clone https://github.com/RVC-Project/Retrieval-based-Voice-Conversion.git rvc
          cd rvc

      - name: Download example input
        run: |
          curl -L -o input.wav https://storage.googleapis.com/chatterbox-demo-samples/samples/numbers_random_woman.wav

      - name: Run RVC Conversion
        run: |
          cd rvc
          # NOTE: Replace model path with a pretrained RVC checkpoint (needs a real model)
          echo "Pretend RVC conversion done here with input.wav -> rvc_output.wav"
          cp ../input.wav ../rvc_output.wav

      - name: Upload RVC sample
        uses: actions/upload-artifact@v4
        with:
          name: rvc_sample
          path: rvc_output.wav
