name: Tortoise-TTS CI

on:
 workflow_dispatch:

jobs:
  run-tortoise:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Free up disk space
        run: |
          sudo apt-get clean
          sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc \
            /usr/local/share/boost /usr/local/share/chromium /usr/share/swift \
            /usr/local/graalvm /opt/hostedtoolcache/CodeQL
          docker system prune -af || true
          sudo rm -rf /var/lib/mysql /var/lib/postgresql
          sudo rm -rf /tmp/*
          sudo rm -rf $HOME/.cargo
          sudo rm -rf $HOME/.gem
          sudo rm -rf $HOME/.rustup
          sudo rm -rf $HOME/.nvm
          sudo rm -rf $HOME/.npm
          sudo rm -rf $HOME/.gradle
          sudo rm -rf $HOME/.cache
          sudo rm -rf /home/runner/.cache
          
      - name: Remove Cache
        run: |
            rm -rf /home/runner/.cache/huggingface/*
          
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Upgrade pip
        run: python -m pip install --upgrade pip
        
      - name: Install PyTorch and Torchaudio
        run: pip install torch torchaudio
        
      - name: Clone Tortoise-TTS repository
        run: git clone https://github.com/neonbjb/tortoise-tts.git
      
      - name: Patch setup.py to relax tokenizers dependency
        run: |
          cd tortoise-tts
          sed -i 's/tokenizers==0.14.0/tokenizers\<0.14/' setup.py
      
      - name: Install Tortoise-TTS (patched)
        run: |
          cd tortoise-tts
          pip install .

      # - name: Install Tortoise TTS
      #   run: pip install git+https://github.com/neonbjb/tortoise-tts.git@7f14bb75fc9c3cd265ec3f456218b51b292f9fa0


      - name: Generate test audio
        run: python run_tort.py
          
      - name: Upload audio
        uses: actions/upload-artifact@v4
        with:
          name: tts-audio
          path: output.wav
